DROP TABLE SPRING_MEMBER;

CREATE TABLE SPRING_MEMBER(
	 MNUM 				VARCHAR2(20)	PRIMARY KEY 
	,MNAME 				VARCHAR2(200)
	,MID 				VARCHAR2(300)	NOT NULL
	,MPW 				VARCHAR2(300)	NOT NULL
	,MGENDER 			VARCHAR2(1)	-- F : 여성, M : 남성
	,MBIRTH 			VARCHAR2(10)
	,MHP 				VARCHAR2(16)	NOT NULL
	,MTEL 				VARCHAR2(16) 
	,MEMAIL 			VARCHAR2(300)	NOT NULL
	,MZONECODE 		    VARCHAR2(6)
	,MROADADDR 			VARCHAR2(500)
	,MROADDETAIL		VARCHAR2(500)	
	,MJIBUNADDR 		VARCHAR2(500)
	,MHOBBY 			VARCHAR2(100)
	,MINFO  			VARCHAR2(300)
	,MPHOTO	 			VARCHAR2(300)
	,DELETEYN 			VARCHAR2(1)		NOT NULL
	,INSERTDATE 		DATE
	,UPDATEDATE 		DATE	
);

--SNS 컬럼 추가
ALTER TABLE SPRING_MEMBER ADD SNSTYPE VARCHAR(10);
ALTER TABLE SPRING_MEMBER ADD SNSID VARCHAR(300);
ALTER TABLE SPRING_MEMBER ADD SNSEMAIL VARCHAR(300);
COMMIT;


-- SYS_C0011108
SELECT A.TABLE_NAME, A.COLUMN_NAME, A.INDEX_NAME
FROM   ALL_IND_COLUMNS A
WHERE  A.TABLE_NAME IN ('KOSMO_PRODUCT');


-- board
DROP TABLE SPRING_BOARD;

CREATE TABLE SPRING_BOARD(
	 BNUM VARCHAR2(20)			PRIMARY KEY 
	,BSUBJECT VARCHAR2(200)		NOT NULL
	,BNAME VARCHAR2(100)		NOT NULL
	,BCONTENT VARCHAR2(2000)
	,BFILE VARCHAR2(300)
	,BPW VARCHAR2(300)
	,DELETEYN VARCHAR2(1)		NOT NULL
	,INSERTDATE DATE
	,UPDATEDATE DATE 
);

ALTER TABLE SPRING_BOARD ADD(BHIT NUMBER DEFAULT 0);
COMMIT;


-- 게시판 좋아요 
DROP TABLE SPRING_BOARD_LIKE;
CREATE TABLE SPRING_BOARD_LIKE (
     BLNUM NUMBER PRIMARY KEY 
    ,MNUM VARCHAR2(20)
    ,BNUM VARCHAR2(20)
    ,LIKE_CNT_1 NUMBER DEFAULT 0 
    ,LIKE_CNT_2 NUMBER DEFAULT 0 
    ,DELETEYN VARCHAR2(1) 
    ,INSERTDATE DATE 
    ,UPDATEDATE DATE
);

SELECT * FROM SPRING_BOARD_LIKE;
DELETE FROM SPRING_BOARD_LIKE;
COMMIT;

-- 댓글 
DROP TABLE SPRING_RBOARD;
CREATE TABLE SPRING_RBOARD (
    RBNUM VARCHAR2(20) PRIMARY KEY 
   ,BNUM VARCHAR2(20) 
   ,RBNAME VARCHAR2(100)
   ,RBCONTENT VARCHAR2(300)    
   ,DELETEYN VARCHAR2(1) 
   ,INSERTDATE DATE 
);

SELECT * FROM SPRING_RBOARD;

DELETE FROM SPRING_RBOARD;
COMMIT;

-- RKBCONTENT 컬럼 사이즈 300 에서 200 으로 변경
ALTER TABLE KOSMO_RBOARD MODIFY (RKBCONTENT VARCHAR2(200));
DESC KOSMO_RBOARD;

-- 상품 =====================================================================
CREATE TABLE KOSMO_PRODUCT(
    KPNUM VARCHAR2(20) PRIMARY KEY
   ,KPID VARCHAR2(20)
   ,KPNAME VARCHAR2(200)
   ,KPCOMPANY VARCHAR2(200)
   ,KPFILE VARCHAR2(200)
   ,KPCNT NUMBER
   ,KPPRICE NUMBER
   ,KPDESC VARCHAR2(2000)
   ,DELETEYN VARCHAR2(1)
   ,INSERTDATE DATE
   ,UPDATEDATE DATE
);

SELECT * FROM KOSMO_PRODUCT;
UPDATE KOSMO_PRODUCT SET KPCNT=100 WHERE 1=1 AND KPNAME = 'name7';



		SELECT 	A.KPNUM 	KPNUM
		       ,A.KPID 		KPID
		       ,A.KPNAME 	KPNAME
		       ,A.KPCOMPANY KPCOMPANY
		       ,A.KPFILE 	KPFILE
		       ,A.KPCNT 	KPCNT
		       ,A.KPPRICE 	KPPRICE
		       ,A.KPDESC 	KPDESC
		       ,A.DELETEYN 	DELETEYN
		       ,TO_CHAR(A.INSERTDATE, 'YYYY-MM-DD') INSERTDATE
		       ,TO_CHAR(A.UPDATEDATE, 'YYYY-MM-DD') UPDATEDATE	 
		       ,CEIL(ROW_NUMBER() OVER(ORDER BY A.KPNUM)/ 10 ) pageSize		
			   ,COUNT(A.KPNUM) OVER() AS totalCount 
		FROM 	KOSMO_PRODUCT A
		WHERE 	A.DELETEYN = 'Y' 	
		ORDER BY 1 DESC;  
	
	
DROP TABLE KOSMO_CART;
CREATE TABLE KOS_CART(
    KCNUM VARCHAR2(20) PRIMARY KEY
   ,KPID VARCHAR2(20)
   ,KPNAME VARCHAR2(200)
   ,KPFILE VARCHAR2(200)
   ,KPCNT NUMBER   
   ,KPPRICE NUMBER
   ,KPPRICESUM NUMBER   
   ,KPNUM VARCHAR2(20) 
   ,KMNUM VARCHAR2(20)
   ,DELETEYN VARCHAR2(1)
   ,INSERTDATE DATE
   ,UPDATEDATE DATE
);

SELECT * FROM KOSMO_CART;

UPDATE KOSMO_CART SET DELETEYN = 'N', UPDATEDATE = SYSDATE WHERE KCNUM = 'C202205220007';
ROLLBACK;

SELECT  /*+ INDEX_DESC(A SYS_C0011214) */
        NVL(MAX(SUBSTR(A.KCNUM, -4)), 0) + 1  KCNUM 
FROM    KOSMO_CART A;

-- SYS_C0011279
SELECT A.TABLE_NAME, A.COLUMN_NAME, A.INDEX_NAME
FROM   ALL_IND_COLUMNS A
WHERE  A.TABLE_NAME IN ('KOSMO_CART');
	



